### ISSUE TITLE
with the basic example, after build and running start you get FST_ERR_DEC_ALREADY_PRESENT

### ISSUE THREAD

**Issue by holmok-bestow** [mcansh/remix-fastify#389]
How to replicate:

1. run `npx create-remix@latest --template mcansh/remix-fastify/examples/basic`
2. `cd` into created app
3. run `npm run build`
4. run `npm start`

...and you get the following error:

```
npm start

> start
> cross-env NODE_ENV=production node --enable-source-maps ./server.js


/Users/chrisholmok/projects/remix-testing/basic/node_modules/fastify/lib/decorate.js:41
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)
          ^
FastifyError [Error]: The decorator 'sendFile' has already been added!
    at decorateConstructor (/Users/chrisholmok/projects/remix-testing/basic/node_modules/fastify/lib/decorate.js:41:11)
    at Object.decorateReply (/Users/chrisholmok/projects/remix-testing/basic/node_modules/fastify/lib/decorate.js:116:3)
    at fastifyStatic (/Users/chrisholmok/projects/remix-testing/basic/node_modules/@fastify/static/index.js:78:13)
    at Plugin.exec (/Users/chrisholmok/projects/remix-testing/basic/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/chrisholmok/projects/remix-testing/basic/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_DEC_ALREADY_PRESENT',
  statusCode: 500
}
```

**Comment by mcansh** [comment]
a couple things, firstly only the “vite” template is considered recommended as Remix will be removing their classic compiler at some point. but to solve your issue it looks like i missed a `decorateReply: false` on one of the fastifyStatic instances, which should solve the issue. let me know if that works and i’ll put up a PR :)
