### ISSUE TITLE
useLoaderData parsing error

### ISSUE THREAD

**Issue by lu-zen** [mcansh/remix-fastify#51]
Idk exactly whats going on, but useLoaderData can't parse my root loader json  data after the first loading. It's serializable and works great with the official express runtime.

Returned loader data is identical btw, weird error.

Started to happen when I upgraded remix deps to 1.7.6

**Comment by machour** [comment]
@mcansh I believe the problem is that headers are not being sent, check this discord entry where Jacob diagnosed the issue: https://discord.com/channels/770287896669978684/1047907012815618159

**Comment by mcansh** [comment]
strange, apply headers here https://github.com/mcansh/remix-fastify/blob/main/packages/remix-fastify/src/server.ts#L108-L114 and if i log them i see them, but the browser isn't getting them, at least not all of them..

**Comment by machour** [comment]
![7gkuki7ktmjozvufjswo](https://user-images.githubusercontent.com/304450/205329828-0f5ca872-347e-4bb6-a2fa-369eeaa29efe.gif)

**Comment by lu-zen** [comment]
A new error
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6109:9)
    at renderNodeDestructiveImpl (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderContextProvider (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:5986:3)
    at renderElement (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:5851:7)
    at renderElement (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (remix-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
```

**Comment by machour** [comment]
@lu-zen please fill a new issue with more details

**Comment by mcansh** [comment]
> @lu-zen please fill a new issue with more details

im able to reproduce, but i have no idea how to fix it currently 😅
