### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by qianjiachun** [mcansh/remix-fastify#75]
Windows  
Node.js v18.14.2
```
"dependencies": {
    "@mcansh/remix-fastify": "^2.6.0",
    "@remix-run/node": "^1.14.1",
    "@remix-run/react": "^1.14.1",
    "fastify": "^4.14.1",
    "isbot": "^3.6.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

1. `npx create-remix@latest --template https://github.com/mcansh/remix-fastify/tree/main/example --no-install`
2. `npm i`
3. `npm run dev`

```
PS D:\Data\code\test\my-remix-fastify-test> npm run dev

> dev
> npm run build && run-p dev:*


> build
> remix build

Building Remix app in production mode...
Built in 619ms

> dev:remix
> remix dev


> dev:server
> node --require dotenv/config --watch ./server.js

(node:1696) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✅ app ready: http://0.0.0.0:3000
Loading environment variables from .env
node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at resolve (node:path:167:9)
    at FSWatcher.<anonymous> (node:internal/watch_mode/files_watcher:94:30)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.14.2
💿 Built in 688ms
ERROR: "dev:server" exited with 1.
```

**Comment by qianjiachun** [comment]
Then I try to build.  
1. `npm run build`
2. `npm run start`
```
Error: SESSION_SECRET must be set
    at Object.<anonymous> (D:\Data\code\test\my-remix-fastify-test\build\index.js:196:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```



I edit the code to make `SESSION_SECRET` a constant.
here is the result:
```
PS D:\Data\code\test\my-remix-fastify-test> npm run start

> start
> node ./server.js

AssertionError [ERR_ASSERTION]: The first character of a path should be `/` or `*`
    at Router.on (D:\Data\code\test\my-remix-fastify-test\node_modules\find-my-way\index.js:107:3)
    at Object.addNewRoute (D:\Data\code\test\my-remix-fastify-test\node_modules\fastify\lib\route.js:310:16)
    at Object.route (D:\Data\code\test\my-remix-fastify-test\node_modules\fastify\lib\route.js:226:19)
    at Object.prepareRoute (D:\Data\code\test\my-remix-fastify-test\node_modules\fastify\lib\route.js:159:18)
    at Object._get [as get] (D:\Data\code\test\my-remix-fastify-test\node_modules\fastify\fastify.js:259:34)
    at remixFastify (D:\Data\code\test\my-remix-fastify-test\node_modules\@mcansh\remix-fastify\src\plugin.ts:111:15) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

maybe it's related to Windows?

**Comment by mcansh** [comment]
unfortunately i can't reproduce this on my windows instance 
![Untitled](https://user-images.githubusercontent.com/11698668/225157285-21ffdfd0-acfe-4558-b9bb-f01df2286737.jpg)

**Comment by mcansh** [comment]
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at resolve (node:path:167:9)
    at FSWatcher.<anonymous> (node:internal/watch_mode/files_watcher:94:30)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

this part may be due to the new dev server, it was throwing that then stopped all of a sudden, let me double check

**Comment by mcansh** [comment]
can you try this diff?

```diff
// remix.config.js
module.exports = {
  // ...
  future: {
-   unstable_dev: true,
    v2_routeConvention: true,
  }
};
```

```diff
// server.js

await app.register(remixFastifyPlugin, {
  build: path.join(process.cwd(), "build/index.js"),
  mode: MODE,
- purgeRequireCacheInDevelopment: false,
+ purgeRequireCacheInDevelopment: true,
});
```

```diff
// package.json
"scripts": {
  "build": "remix build",
  "dev:remix": "remix dev",
  "dev:server": "node --require dotenv/config --watch ./server.js",
  "dev": "npm run build && run-p dev:*",
  "start": "node ./server.js"
}
```

**Comment by qianjiachun** [comment]
> > TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
> > at new NodeError (node:internal/errors:399:5)
> > at validateString (node:internal/validators:163:11)
> > at resolve (node:path:167:9)
> > at FSWatcher. (node:internal/watch_mode/files_watcher:94:30)
> > at FSWatcher.emit (node:events:513:28)
> > at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) {
> > code: 'ERR_INVALID_ARG_TYPE'
> > }
> 
> this part may be due to the new dev server, it was throwing that then stopped all of a sudden, let me double check


I found that when I use `nodemon` instead of `node`, it can also worked. Whether the new dev is used or not.
But it only solves the problem of ` The "path" argument must be of type string Received null`.


```
// package.json
"scripts": {
    "build": "remix build",
    "dev:remix": "remix dev",
    "dev:server": "cross-env NODE_ENV=development nodemon --require dotenv/config ./server.js --watch ./server.js",
    "dev": "npm run build && run-p dev:*",
    "start": "node ./server.js"
  }
```

```
PS E:\Code\test\remix-fastify-test> npm run dev

> dev
> npm run build && run-p dev:*


> build
> remix build

Building Remix app in production mode...
Built in 406ms

> dev:server
> cross-env NODE_ENV=development nodemon --require dotenv/config ./server.js --watch ./server.js


> dev:remix
> remix dev

[nodemon] 2.0.21
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --require dotenv/config ./server.js`
✅ app ready: http://0.0.0.0:3000
Loading environment variables from .env
💿 Built in 638ms
No routes matched location "/modules/_assets/global-AX5QYKSR.css" 
No routes matched location "/modules/manifest-024802BA.js" 
No routes matched location "/modules/entry.client-P6EBOJLM.js"
No routes matched location "/modules/root-COQ7QQQM.js"
No routes matched location "/modules/_shared/chunk-AAVDB6VW.js" 
No routes matched location "/modules/routes/_layout-JULKL2AY.js"
No routes matched location "/modules/routes/_layout._index-FDZPEXBK.js" 
No routes matched location "/modules/_assets/global-AX5QYKSR.css" 
No routes matched location "/modules/entry.client-P6EBOJLM.js" 
No routes matched location "/modules/manifest-024802BA.js"
No routes matched location "/modules/root-COQ7QQQM.js"
No routes matched location "/modules/_shared/chunk-AAVDB6VW.js"
No routes matched location "/modules/routes/_layout-JULKL2AY.js" 
No routes matched location "/modules/routes/_layout._index-FDZPEXBK.js"
```
